apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
  labels:
    app: tpfoyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: tasnimbenkhalifa/tpfoyer:latest
          imagePullPolicy: Always   # Force Kubernetes Ã  tirer l'image depuis Docker Hub
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
spec:
  selector:
    app: tpfoyer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort   # Pour exposer le service sur Minikube
