apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
spec:
  type: NodePort
  selector:
    app: tpfoyer
  ports:
    - protocol: TCP
      port: 8081       # Port interne dans le cluster
      targetPort: 8081 # Port du conteneur
      nodePort: 30185  # Port expos√© sur Minikube
